version: '3'
services:
  klevr-webconsole:
    image: klevry/webconsole:latest
    environment:
            - API_SERVER=http://client:8500
    links:
      - client:client
    ports:
      - "8080:8080"
  seed:
    hostname: seed
    image: consul:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - "engine.labels.access == consul_seed"
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - "CONSUL_BIND_INTERFACE=ens5"
      - "CONSUL_DATA_DIR=/consul/data"
      - "CONSUL_CONFIG_DIR=/consul/config"
    entrypoint:
      - consul
      - agent
      - -server
      - -bootstrap-expect=1
      - -data-dir=/tmp/consuldata
      - -dns-port=53
      - -recursor=8.8.8.8
      - -client=0.0.0.0
      - -datacenter=klevr
      - -encrypt=ciywsCiiChneJgljvQqJTg==
      - -bind={{ GetInterfaceIP "eth0" }}
    volumes:
      - ./kvstore/conf_seed/:/tmp/consuldata
  cluster:
    image: consul:latest
    hostname: cluster
    depends_on:
      - "seed"
    deploy:
      mode: global                                      ##this will deploy to all nodes that
      placement:
        constraints:
          - "engine.labels.access != consul_seed"
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - "CONSUL_BIND_INTERFACE=ens5"
      - "CONSUL_DATA_DIR=/consul/data"
      - "CONSUL_CONFIG_DIR=/consul/config"
    entrypoint:
      - consul
      - agent
      - -server
      - -data-dir=/tmp/consuldata
      - -bind={{ GetInterfaceIP "eth0" }}
      - -recursor=8.8.8.8
      - -dns-port=53
      - -client=0.0.0.0
      - -datacenter=klevr
      - -encrypt=ciywsCiiChneJgljvQqJTg==
      - -retry-join=seed:8301
    volumes:
      - ./kvstore/conf_cluster/:/tmp/consuldata
  client:
    image: consul:latest
    hostname: client
    depends_on:
      - "seed"
    deploy:
      mode: global                                      ##this will deploy to all nodes that
      placement:
        constraints:
          - "engine.labels.access != consul_seed"
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - "CONSUL_BIND_INTERFACE=ens5"
      - "CONSUL_DATA_DIR=/consul/data"
      - "CONSUL_CONFIG_DIR=/consul/config"
    entrypoint:
      - consul
      - agent
      - -data-dir=/tmp/consuldata
      - -recursor=8.8.8.8
      - -dns-port=53
      - -client=0.0.0.0
      - -datacenter=klevr
      - -encrypt=ciywsCiiChneJgljvQqJTg==
      - -retry-join=seed:8301
      - -bind={{ GetInterfaceIP "eth0" }}
      - -ui                                              ##assuming you want the UI on
    volumes:
      - ./kvstore/conf_client/:/tmp/consuldata
    ports:
      - "8600:53"
      - "8600:53/udp"
      - "8500:8500"
